version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: 'java-postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: person
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5b6eu5
    volumes:
      - ~/pgdata:/var/lib/postgresql/data

  app:
    build: ./
    container_name: 'perspr'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://java-postgres:5432/person
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 5b6eu5
    ports:
      - "8080:8080"

#  pgadmin:
#    container_name: pgAdminSelfGuru
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: lxqtpr@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: lxqtpr2021
#    ports:
#      - "5050:80"
